# Generated by Django 5.2.15 on 2026-08-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
