# Generated by Django 5.2.15 on 2026-08-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_image', models.URLField(blank=True, max_length=1000)),
                ('short_description', models.CharField(max_length=500)),
                ('detailed_description', models.TextField()),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('custom_dates', models.JSONField(blank=True, default=dict)),
                ('registration_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('registration_link_clicks', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('map_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='event.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'student'], name='event_event_event_i_78d684_idx'), models.Index(fields=['student', '-created_at'], name='event_event_student_aa1964_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'student'), name='unique_event_interest')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registration_clicks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_click_logs', to='event.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', '-clicked_at'], name='event_event_event_i_d886b8_idx'), models.Index(fields=['clicked_at'], name='event_event_clicked_ef90cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='event.event')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', '-viewed_at'], name='event_event_event_i_54d7d0_idx'), models.Index(fields=['viewer', 'event', '-viewed_at'], name='event_event_viewer__b3728b_idx')],
            },
        ),
    ]
