# Generated by Django 5.2.15 on 2026-07-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_custom_dates_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
