# Generated by Django 5.2.15 on 2026-08-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventregistrationclick'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventregistrationclick',
            new_name='event_event_event_i_d886b8_idx',
            old_name='event_event_event_i_7782ca_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistrationclick',
            new_name='event_event_clicked_ef90cc_idx',
            old_name='event_event_clicked_82c89c_idx',
        ),
    ]
