# Generated by Django 5.2.15 on 2026-08-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventinterest_eventview'),
        ('event', '0003_rename_event_event_event_i_7782ca_idx_event_event_event_i_d886b8_idx_and_more'),
    ]

    operations = [
    ]
