# Generated by Django 5.2.15 on 2026-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='online_meeting_link',
            new_name='registration_link',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
