# Generated by Django 5.2.15 on 2026-08-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_merge_20260802_1757'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventinterest',
            new_name='event_event_event_i_78d684_idx',
            old_name='event_event_event_i_050887_idx',
        ),
        migrations.RenameIndex(
            model_name='eventinterest',
            new_name='event_event_student_aa1964_idx',
            old_name='event_event_student_3af2c8_idx',
        ),
        migrations.RenameIndex(
            model_name='eventview',
            new_name='event_event_event_i_54d7d0_idx',
            old_name='event_event_event_i_c06205_idx',
        ),
        migrations.RenameIndex(
            model_name='eventview',
            new_name='event_event_viewer__b3728b_idx',
            old_name='event_event_viewer__d13fd3_idx',
        ),
    ]
