# Generated by Django 5.2.15 on 2026-07-18 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabrationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_mode', models.CharField(max_length=20)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('event_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('team_size', models.PositiveIntegerField()),
                ('members_required', models.PositiveIntegerField(default=1)),
                ('skills', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
