# Generated by Django 5.2.15 on 2026-07-27 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('usercollabration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollabratiEventPost',
            new_name='CollabrationEventPost',
        ),
    ]
