# Generated by Django 5.2.15 on 2026-08-04 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollabration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.CharField(blank=True, max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_url', models.URLField()),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('roles_needed', models.JSONField(blank=True, default=list)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('contributors_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Looking for Contributors', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opensource_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
