# Generated by Django 5.2.15 on 2026-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollabration', '0002_opensourceproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabrationeventpost',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
