# Generated by Django 5.2.15 on 2026-08-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercollabration', '0003_collabrationeventpost_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensourceproject',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='opensourceproject',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='opensourceproject',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='opensourceproject',
            name='stars',
        ),
    ]
