# Generated by Django 5.2.15 on 2026-08-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delete_for_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_for_this', to=settings.AUTH_USER_MODEL),
        ),
    ]
