# Generated by Django 5.2.15 on 2026-08-05 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('usercollabration', '0002_opensourceproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('event', 'Event'), ('project', 'Open source project'), ('collabration', 'Collabration post')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collabration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='usercollabration.collabrationeventpost')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='event.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='usercollabration.opensourceproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'item_type', '-created_at'], name='saved_saved_user_id_c7de60_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_saved_event'), models.UniqueConstraint(fields=('user', 'project'), name='unique_saved_project'), models.UniqueConstraint(fields=('user', 'collabration'), name='unique_saved_collabration')],
            },
        ),
    ]
