# Generated by Django 5.2.15 on 2026-08-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_team_name_alter_team_event_and_more'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaceRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.BigIntegerField()),
                ('repo_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('default_branch', models.CharField(max_length=100)),
                ('html_url', models.URLField()),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
