# Generated by Django 5.2.15 on 2026-08-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspacerepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacerepository',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
