# Generated by Django 5.2.15 on 2026-08-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_organizationfollow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationfollow',
            new_name='network_org_student_f7741b_idx',
            old_name='network_org_student_64c42a_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationfollow',
            new_name='network_org_organiz_4b42d4_idx',
            old_name='network_org_organiz_7df8ed_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationfollow',
            new_name='network_org_student_74d266_idx',
            old_name='network_org_student_5dbf87_idx',
        ),
    ]
