# Generated by Django 5.2.15 on 2026-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationstore_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
