# Generated by Django 5.2.15 on 2026-07-14 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='organization_type',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='logo',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
