# Generated by Django 5.2.15 on 2026-08-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganizationProfile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofileview',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofileview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_organization_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationprofileview',
            index=models.Index(fields=['organization', '-viewed_at'], name='Organizatio_organiz_673f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationprofileview',
            index=models.Index(fields=['viewer', 'organization', '-viewed_at'], name='Organizatio_viewer__feb692_idx'),
        ),
    ]
