# Generated by Django 5.2.15 on 2026-07-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationProfile', '0002_rename_organization_type_organizationprofile_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='founded_year',
        ),
    ]
