# Generated by Django 5.2.15 on 2026-08-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationProfile', '0003_organizationprofileview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationprofileview',
            new_name='Organizatio_organiz_673f2b_idx',
            old_name='Organizatio_organiz_e4ec07_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationprofileview',
            new_name='Organizatio_viewer__feb692_idx',
            old_name='Organizatio_viewer__d23ed8_idx',
        ),
    ]
