# Generated by Django 5.2.15 on 2026-07-13 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.URLField(null=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255, null=True)),
                ('school', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('bio', models.TextField(null=True)),
                ('experience', models.TextField()),
                ('preferred_role', models.CharField(max_length=150)),
                ('selectedSkills', models.JSONField(default=list)),
                ('git_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
