# Generated by Django 5.2.15 on 2026-08-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
