# Generated by Django 5.2.15 on 2026-08-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_githubtokens'),
        ('profiles', '0002_userprofile_portfolio_link_alter_userprofile_bio_and_more'),
    ]

    operations = [
    ]
