# Generated by Django 5.2.15 on 2026-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_bio_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
