# Generated by Django 5.2.15 on 2026-08-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_savedcollaborationpost_savedevent_and_more'),
        ('profiles', '0002_userprofile_embedding'),
    ]

    operations = [
    ]
