# Generated by Django 5.2.15 on 2026-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20260803_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtokens',
            name='github_username',
            field=models.CharField(null=True),
        ),
    ]
