# Generated by Django 5.2.15 on 2026-07-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercollabration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.PositiveIntegerField()),
                ('members_required', models.PositiveIntegerField(default=1)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('roles', models.JSONField(blank=True, default=list, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercollabration.collabratieventpost')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'member'), name='unique_team_member')],
            },
        ),
    ]
