# Generated by Django 5.2.15 on 2026-08-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('usercollabration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usercollabration.collabrationeventpost'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_required',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
