# Generated by Django 5.2.15 on 2026-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='role',
        ),
    ]
