# Generated by Django 5.2.15 on 2026-07-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_teammembers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
